config/routes.rb
Rails.application.routes.draw do

  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  post 'scheme' => "scarves#scheme", :as => :pull_scheme

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  resources :scarves

  # get 'scheme', to: 'scarves#scheme', as: 'scheme'

  root "landing#index"

  get 'patterns/new'
  get 'patterns/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/scarves_controller.rb
class ScarvesController < ApplicationController
  before_action :set_scarf, only: [:show, :edit, :update, :destroy]

  # GET /scarves
  # GET /scarves.json
  def index
    @scarves = Scarf.all.order("updated_at DESC")

    @scarves = @scarves.scarf_name(params[:scarf_name].strip) if params[:scarf_name].present?
    @scarves = @scarves.descrip(params[:description].strip) if params[:description].present?

  end

  # GET /scarves/1
  # GET /scarves/1.json
  def show

  end

  # GET /scarves/new
  def new
    @scarf = Scarf.new
  end

  def scheme
    base_color = params['baseColor'][1..-1]
    pallete_num = params['palleteNum']
    scheme_type = params['schemeType']

    response = HTTParty.get("http://thecolorapi.com/scheme?hex=#{base_color}&mode=#{scheme_type}&count=#{pallete_num}")
    scheme_cols = response['colors']

    respond_to do |format|
        format.html { redirect_to scarf_path(Scarf.find(4)), notice: "Here's your new colours" }
        format.json { render json: response}
    end


    # return redirect_to scarf_path(Scarf.find(4)), notice: "#{base_color}"
  end

  # GET /scarves/1/edit
  def edit
    if not_allowed?
      return redirect_to scarf_path(@scarf), notice: "Sorry. You do not have the permission to edit a scarf that you didn't make yourself."
    end
  end

  # POST /scarves
  # POST /scarves.json
  def create
    @scarf = Scarf.new(scarf_params)
    @scarf.user = current_user
    unixtime = @scarf.date_insp.to_time.to_i
    glat = @scarf.city.lat
    glng = @scarf.city.lng

    response = HTTParty.get("https://api.darksky.net/forecast/#{ENV['DARK_SKY_SECRET']}/#{glat},#{glng},#{unixtime}?exclude=currently,flags")

    rawpattern = []

    #parse resonse to make pattern
    response['hourly']['data'].each do |hour|\
      str = scarf_params['weather_insp']
      rawpattern << hour["#{str}"]
    end

    @scarf.pattern = rawpattern

    respond_to do |format|
      if @scarf.save
        format.js   {  }
        format.html { redirect_to @scarf, notice: 'Scarf was successfully created.' }
        format.json { render :show, status: :created, location: @scarf }
      else
        format.html { render :new }
        format.json { render json: @scarf.errors, status: :unprocessable_entity }
      end
    end
  end



  # PATCH/PUT /scarves/1
  # PATCH/PUT /scarves/1.json
  def update
    respond_to do |format|
      if @scarf.update(scarf_params)

        unixtime = @scarf.date_insp.to_time.to_i
        glat = @scarf.city.lat
        glng = @scarf.city.lng

        response = HTTParty.get("https://api.darksky.net/forecast/#{ENV['DARK_SKY_SECRET']}/#{glat},#{glng},#{unixtime}?exclude=currently,flags")

        rawpattern = []

        #parse resonse to make pattern
        response['hourly']['data'].each do |hour|\
          str = scarf_params['weather_insp']
          rawpattern << hour["#{str}"]
        end        

        @scarf.update(pattern: rawpattern)
        format.html { redirect_to @scarf, notice: 'Scarf was successfully updated.' }
        format.json { render :show, status: :ok, location: @scarf }
      else
        format.html { render :edit }
        format.json { render json: @scarf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scarves/1
  # DELETE /scarves/1.json
  def destroy
    if not_allowed?
      return redirect_to scarf_path(@scarf), notice: "Sorry. You do not have the permission to delete a scarf that you didn't make yourself."      
    else
      @scarf.destroy
      respond_to do |format|
        format.html { redirect_to scarves_url, notice: 'Scarf was successfully destroyed.' }
        format.json { head :no_content }
      end
    end


  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scarf
      @scarf = Scarf.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scarf_params
      params.require(:scarf).permit(:title, :description, :city_id, :date_insp, :weather_insp)
    end

    def not_allowed?
      current_user == nil or !(current_user.superadmin? or @scarf.user == current_user)
    end

end

app/helpers/scarves_helper.rb
module ScarvesHelper
end

app/views/scarves/_colselect.html.erb
<%= form_with(url:pull_scheme_path, id: 'pallete-maker') do |form| %>
        
    <div class="form-group ">
      <label for="baseColor" class="col-sm-4 col-form-label">Select a main colour:</label>
      <input type="color" name="baseColor" value="#29339B" id="baseColor">
      <button id="gen-random-col">Get random color</button>
    </div>

    <div class="form-group">
      <label for="palleteNum" class="col-sm-4">Select number of colours:</label>
      <div class="text-center font-weight-bold" id="display-pallete-num"></div>
      <input type="range" name="palleteNum" min="3" max="8" value="5" class="slider" id="palleteNum">
    </div>

    <div class="form-inline">
      <label for="schemeType" class="col-sm-4">Select colour scheme type:</label>
      <select class="form-control" name="schemeType" id="schemeType">
        <option value="monochrome">Monochrome</option>
        <option value="monochrome-dark">Dark monochrome</option>
        <option value="monochrome-light">Light monochrome</option>
        <option value="analogic">Analogic</option>
        <option value="complement">Complementary</option>
        <option value="analogic-complement">Analogic-complementary</option>
        <option value="triad">Triad</option>
        <option value="quad">Quad</option>
      </select>
    </div>

    <button type="submit" class="btn btn-secondary">Get colour scheme</button>

<% end %>

app/views/scarves/_form.html.erb
<%= form_with(model: scarf) do |form| %>
  <% if scarf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scarf.errors.count, "error") %> prohibited this scarf from being saved:</h2>

      <ul>
      <% scarf.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :city_id %>
    <%= form.select(:city_id, options_from_collection_for_select(City.all, :id, :city_name, @scarf.city_id.to_i)) %>
  </div>


  <div class="field">
    <%= form.label :date_insp %>
    <%= form.date_select :date_insp %>
  </div>

  <div class="field">
    <%= form.label :weather_insp %>
    <%= form.select(:weather_insp, options_for_select([['Temperature', 'temperature'], ['Humidity', 'humidity'], ['Dew Point', 'dewPoint'], ['Apparent Temperature','apparentTemperature'], ['Wind Speed', 'windSpeed'], ['Cloud Cover', 'cloudCover'], ['Visibility', 'visibility'], ['Summary', 'summary']], [@scarf.weather_insp])) %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/scarves/_scarf.html.erb
<tr>
    <td><%= link_to "#{scarf.title}", scarf %></td>
    <td><%= scarf.description %></td>
    <td><%= scarf.city.city_name %></td>
    <td><%= scarf.date_insp.strftime("%d %b %Y") %></td>
    <td><%= scarf.weather_insp %></td>
    <td><canvas id=<%= "scarf-canvas-#{scarf.id}"%> width="240" height="15"></canvas></td>
    <%if scarf.user == current_user or (!(current_user==nil) and current_user.superadmin?) %>
	    <td><%= link_to 'Edit', edit_scarf_path(scarf) %></td>
	    <td><%= link_to 'Destroy', scarf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% end %>
</tr>

app/views/scarves/_search.html.erb
<div class="form mb-3">
    <%= form.text_field :scarf_name, placeholder: "Any text in the title", class: "form-control mr-2", scarf: "scarf_name" %>
    <%= form.text_field :description, placeholder: "Any text in description", class: "form-control mr-2", scarf: "scarf_desc"  %>
    <%= form.submit "Search", class: "btn btn-outline-danger" %>
</div>

app/views/scarves/create.js.erb
$('#new-scarf form').remove();
$('#new-scarf a').show();
$('table#all-scarves tbody').append("<%= j render @scarf %>")

app/views/scarves/edit.html.erb
<h1>Editing Scarf</h1>

<%= render 'form', scarf: @scarf %>

<%= link_to 'Show', @scarf %> |
<%= link_to 'Back', scarves_path %>

app/views/scarves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scarves</h1>

<div id="search-scarves-display" class="m-3">
  <h5>Search scarves</h5>
  <%= form_with model: @scarf, method: :get, local: true do |form| %>
      <%= render partial: 'search', locals: {form: form} %>
  <% end %>
</div>

<table id="all-scarves">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>City inspiration</th>
      <th>Date inspiration</th>
      <th>Weather inspiration</th>
      <th>Preview</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <%= render partial: 'scarf', collection: @scarves %>
  </tbody>
</table>

<br>

<div id="new-scarf">
  <%if !(current_user == nil)%>
    <%= link_to 'New Scarf', new_scarf_path, remote: true %>  
  <% end %>
</div>

app/views/scarves/new.html.erb
<h1>New Scarf</h1>

<%= render 'form', scarf: @scarf %>

<%= link_to 'Back', scarves_path %>

app/views/scarves/new.js.erb
$('#new-scarf a').hide().parent().append("<%= j render 'form', scarf: @scarf %>")

app/views/scarves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @scarf.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @scarf.description %>
</p>

<p>
  <strong>Made by:</strong>
  <%= @scarf.user.email %>
</p>

<p>
  <strong>City inspiration:</strong>
  <%= @scarf.city.city_name %>
</p>

<p>
  <strong>Date inspiration:</strong>
  <%= @scarf.date_insp %>
</p>

<p>
  <strong>Weather inspiration:</strong>
  <%= @scarf.weather_insp %>
</p>

<p>
  <strong>Pattern:</strong>
  <span id="refPat"><%= @scarf.pattern %></span>
</p>

  <div>
    <canvas id="scarfCanvas" width="720" height="120"></canvas>
  </div>

<% if current_user == @scarf.user %>
<div class="container">
  <div class="row">
    <div class="col-sm-6 border border-danger rounded">
      <h5>Customise colour scheme</h5>
      <%= render 'colselect', scarf: @scarf %>
    </div>

    <div class="col-sm-6 border border-secondary rounded">
      <h5>Preview colour scheme</h5>
      <div id="color-pallete-preview">

      </div>
    </div>
  </div>
</div>
<% end %>


<script>
  var slider = document.getElementById("palleteNum");
  var output = document.getElementById("display-pallete-num");
  output.innerHTML = slider.value;

  slider.oninput = function() {
    output.innerHTML = this.value;
  }

  function getRandomHex() {
    var letters = '0123456789ABCDEF'.split('');
    var color = '#';
    for (var i = 0; i < 6; i++ ) {
      color += letters[Math.floor(Math.random() * 16)];
    }
    return color;
  }

  $('#gen-random-col').click(function(){
    event.preventDefault();
    $('#baseColor').val(getRandomHex())
  })

  $('#pallete-maker').submit(function(){
    event.preventDefault();
    let form = $(this);
    let url = form.attr('action');

    $.ajax({
      method: "POST", // Set request type
      url: url, // Set URL for AJAX to point to
      data: {"pallete_num": "H1"}
    }) 
    .done(function(response) {
      // 2. What to do after receiving a response from the server
      console.log($('#baseColor').val())
      console.log($('#schemeType').val())
      console.log($('#palleteNum').val())
    })



  });

</script>

<script>
  function drawAll(){
    let canvas = document.getElementById('scarfCanvas');
    let canvasContext = canvas.getContext('2d');

    let referenceArray = $('#refPat').html().slice(1,-1).replace(/"/g, "").split(',')

    let highRef = Math.max(...referenceArray);
    let lowRef = Math.min(...referenceArray);
    let range = highRef - lowRef
    let patternMatch = [lowRef, lowRef + range/5, lowRef + 2*range/5, lowRef + 3*range/5, highRef]

    let colorPallete = ['#29339B', '#74A4BC', '#B6D6CC', '#F1FEC6', '#FF3A20']

    function colorRect(leftX, topY, width, height, drawColor){
      canvasContext.fillStyle = drawColor;
      canvasContext.fillRect(leftX, topY, width, height);
      }

      for (var i = 0 ; i < 24; i++) {
        if(referenceArray[i] > patternMatch[4] ){
          colorRect(i * canvas.width/24, 0,canvas.width/24,canvas.height, colorPallete[0])
        } else if(referenceArray[i] > patternMatch[3] ){
          colorRect(i * canvas.width/24, 0,canvas.width/24,canvas.height, colorPallete[4])
        } else if(referenceArray[i] > patternMatch[2] ){
          colorRect(i * canvas.width/24, 0,canvas.width/24,canvas.height, colorPallete[2])
        } else if(referenceArray[i] > patternMatch[1] ){
          colorRect(i * canvas.width/24, 0,canvas.width/24,canvas.height, colorPallete[3])
        } else {
          colorRect(i * canvas.width/24, 0,canvas.width/24,canvas.height, colorPallete[1])
        }
      }

  };

  $(document).ready(function(){
    drawAll();
  })

</script>

<%= link_to 'Edit', edit_scarf_path(@scarf) %> |
<%= link_to 'Back', scarves_path %>