config/routes.rb
Rails.application.routes.draw do

  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  post 'scheme' => "scarves#scheme", :as => :pull_scheme

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  resources :scarves

  # get 'scheme', to: 'scarves#scheme', as: 'scheme'

  root "landing#index"

  get 'patterns/new'
  get 'patterns/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/patterns_controller.rb
class PatternsController < ApplicationController
  def new
  	@timestamp = Date.new(2019,02,18).to_time.to_i
  end

  def show
  	response = HTTParty.get("https://api.darksky.net/forecast/#{ENV['DARK_SKY_SECRET']}/42.3601,-71.0589,255657600?exclude=currently,flags")
  end

end

app/helpers/patterns_helper.rb
module PatternsHelper
end

app/views/patterns/_form.html.erb
<%= form_tag(patterns_show_path, :method => "get") do %>
  <div class="field">
    <%= label_tag(:date, "The weather on this day:") %>
    <%= select_date %>
  </div>

  <div>
  	<%= submit_tag("Make a pattern")%>
  </div>

<% end %>

app/views/patterns/new.html.erb
<h1>Patterns#new</h1>
<p>Find me in app/views/patterns/new.html.erb</p>

<%= @timestamp%>
<%= render 'form' %>

app/views/patterns/show.html.erb
<h1>Patterns#show</h1>
<p>Find me in app/views/patterns/show.html.erb</p>

<%= response.body %>